TILE_COUNTER: .byte 0
TILE_NUMBER:  .byte 0
TILE_TEMP_X:  .byte 0
TILE_TEMP_Y:  .byte 0
MAP_NUMBER:   .byte 0
MAP_TEMP_X:   .byte 0
MAP_TEMP_Y:   .byte 0
TILE_ROW:     .byte 0
TILE_COL:     .byte 0
MAP_ROW:      .byte 0
MAP_COL:      .byte 0