// ----------- VARIABLES -----------
#import "/variables/strings.asm"
#import "/variables/print_lib_variables.asm"
#import "/variables/math_lib_variables.asm"
#import "/variables/input_lib_variables.asm"
#import "/variables/joystick_lib_variables.asm"
#import "/variables/sprites_lib_variables.asm"
#import "/variables/concurrence_variables.asm"
#import "/variables/tiles_lib_variables.asm"
#import "/variables/sound_lib_variables.asm"